<?php
/* @var Codilar\HelloWorld\Block\Hello $block */
$cars = $block->getAllCars();
?>

<form method="post" action="<?= $block->getAddCarPostUrl() ?>">
   <fieldset>
       <div>
            <label for="manufacturer"><?= __("Manufacturer") ?></label>
           <input type="text" name="manufacturer" id="manufacturer" />
      </div>
       <div>
            <label for="model"><?= __("Model") ?>
           <input type="text" name="model" id="model" />
       </div>
      <input type="submit" value="<?= __("Add Car") ?>" />
   </fieldset>
</form>
<hr />
<?php if (count($cars) > 0): ?>
 <table border="1">
      <tr>
         <th><?= __("ID") ?></th>
          <th><?= __("Manufacturer") ?>
            <?= __("Model") ?></th>
        </tr>
       <?php foreach ($cars as $car): ?>
            <tr>
               <td><?= $car->getId() ?>
               <td><?= $car->getManufacturer() ?>
              <td><?= $car->getModel() ?>
           </tr>
      <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1><?= __("You have no cars yet :(") ?></h1>
<?php endif; ?>